### ISSUE TITLE
Unable to add session to handshake

### ISSUE THREAD

**Issue by skinneejoe** [leeroybrun/socketio-express-sessions#4]
In your code example is says:

    // If you want, you can attach the session to the handshake data, so you can use it again later
    // You can access it later with "socket.handshake.session"
    data.session = session;

If I do this, I cannot see the session data in handshake on any subsequent socket events. However, if I attach the session to data.__*headers*__.session instead, then I can access it on subsequent socket events via socket.handshake.headers.session. I'm using the newly released SocketIO 1.0, maybe something changed and the handshake object is now unchangeable? Is it acceptable to place the session data in socket.handshake.headers.session or does this pose any security risks?

**Comment by leeroybrun** [comment]
Sorry for the HUGE delay... Have you found a solution?

My example was not compatible for SockerIO 1.0 at this time.   

I've updated it two months ago and now it is fully compatible for SocketIO 1 and Express 4.

Here is the part where you add data to the session : https://github.com/leeroybrun/socketio-express-sessions/blob/master/server.js#L104

And then you can use it like this : https://github.com/leeroybrun/socketio-express-sessions/blob/master/server.js#L121

**Comment by skinneejoe** [comment]
Thanks for the update! Better late than never! ;^)

I can't recall what solution I found, but I worked around it somehow. But your solution will be nice moving forward. Thanks!
