### ISSUE TITLE
How to redirect user if he already logout

### ISSUE THREAD

**Issue by Stayer** [leeroybrun/socketio-express-sessions#5]
How to redirect user to login if he already logged out from site?

I tried to redirect already logged out user. I opened 2 browser tabs, on first i click on "Logout", but on second tab disconnect not happens. How to solve this problem? How to check "if user already logged out"?

I need some function like this (from express.sessions)
function restrict(req, res, next) {
    if (req.session.isLogged) {
        console.log("AUTH: "+ req.session.username + " (id=" + req.session.userid +") has successfully logged in!");
        next();
    } else {
        req.session.error = 'Problem, man?';
        res.redirect('/login');
    }
}

**Comment by leeroybrun** [comment]
So you want to be able to redirect the user to login if he logs out from an other window/tab ?

**Comment by Stayer** [comment]
Yes. Or instantly redirect to login page, if user logout from other tab

**Comment by leeroybrun** [comment]
Sorry for the late reply...

I think you can just register to the "disconnect" event on the client side, and when it occurs, trigger the browser to redirect:

Add this here : https://github.com/leeroybrun/socketio-express-sessions/blob/master/views/index.html#L88

    socket.on('disconnect', function() {
        alert('client socketio disconnect!');
        window.location = '/login';
    });
